// <auto-generated />
using JunkyardWebApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JunkyardWebApp.API.Migrations
{
    [DbContext(typeof(JunkyardContext))]
    [Migration("20221107054725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JunkyardWebApp.API.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarId"));

                    b.Property<int>("Colour")
                        .HasColumnType("integer");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Colour = 1,
                            Make = "Toyota",
                            Model = "Corolla",
                            Year = 2005
                        },
                        new
                        {
                            CarId = 2,
                            Colour = 2,
                            Make = "Ford",
                            Model = "Falcon",
                            Year = 1995
                        },
                        new
                        {
                            CarId = 3,
                            Colour = 3,
                            Make = "Honda",
                            Model = "Accord",
                            Year = 2012
                        },
                        new
                        {
                            CarId = 4,
                            Colour = 5,
                            Make = "Nissan",
                            Model = "Silvia",
                            Year = 2003
                        });
                });

            modelBuilder.Entity("JunkyardWebApp.API.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartId"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("PartId");

                    b.HasIndex("CarId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            CarId = 1,
                            Category = 0,
                            Description = "Engine for 2005 Corolla",
                            Price = 1500.00m
                        },
                        new
                        {
                            PartId = 2,
                            CarId = 1,
                            Category = 7,
                            Description = "Exhaust for 2005 Corolla",
                            Price = 700.00m
                        },
                        new
                        {
                            PartId = 3,
                            CarId = 1,
                            Category = 6,
                            Description = "Front Passenger Door for 2005 Corolla",
                            Price = 200.00m
                        },
                        new
                        {
                            PartId = 4,
                            CarId = 1,
                            Category = 8,
                            Description = "Taillights for 2005 Corolla",
                            Price = 30.00m
                        },
                        new
                        {
                            PartId = 5,
                            CarId = 1,
                            Category = 4,
                            Description = "Wheels for 2005 Corolla",
                            Price = 450.00m
                        },
                        new
                        {
                            PartId = 6,
                            CarId = 2,
                            Category = 5,
                            Description = "Tyres for 1995 Falcon",
                            Price = 360.00m
                        },
                        new
                        {
                            PartId = 7,
                            CarId = 2,
                            Category = 3,
                            Description = "Brakes for 1995 Falcon",
                            Price = 820.00m
                        },
                        new
                        {
                            PartId = 8,
                            CarId = 2,
                            Category = 1,
                            Description = "Radiator for 1995 Falcon",
                            Price = 120.00m
                        },
                        new
                        {
                            PartId = 9,
                            CarId = 2,
                            Category = 2,
                            Description = "Suspension for 1995 Falcon",
                            Price = 300.00m
                        },
                        new
                        {
                            PartId = 10,
                            CarId = 3,
                            Category = 0,
                            Description = "Engine for 2012 Accord",
                            Price = 1750.00m
                        },
                        new
                        {
                            PartId = 11,
                            CarId = 3,
                            Category = 8,
                            Description = "Brake light for 2012 Accord",
                            Price = 55.00m
                        },
                        new
                        {
                            PartId = 12,
                            CarId = 3,
                            Category = 6,
                            Description = "Rear driver door for 2012 Accord",
                            Price = 190.00m
                        },
                        new
                        {
                            PartId = 13,
                            CarId = 4,
                            Category = 7,
                            Description = "Exhaust for 2003 Silvia",
                            Price = 290.00m
                        },
                        new
                        {
                            PartId = 14,
                            CarId = 4,
                            Category = 3,
                            Description = "Headlight for 2003 Silvia",
                            Price = 370.00m
                        });
                });

            modelBuilder.Entity("JunkyardWebApp.API.Models.Part", b =>
                {
                    b.HasOne("JunkyardWebApp.API.Models.Car", "Car")
                        .WithMany("AvailableParts")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("JunkyardWebApp.API.Models.Car", b =>
                {
                    b.Navigation("AvailableParts");
                });
#pragma warning restore 612, 618
        }
    }
}
